table inet filter {
  chain output {
    type filter hook output priority filter
    policy accept
    counter accept
  }

  chain input {
    type filter hook input priority filter
    policy drop

    ct state { established, related } counter accept
    ct state invalid counter drop

    ip protocol icmp icmp type {
      echo-request,
      destination-unreachable,
      time-exceeded,
      parameter-problem,
    } counter accept

    iifname {
      "lo",
      "eno1",
      "tailscale0",
    } counter accept comment "Allow trusted interfaces to router"
  }

  chain forward {
    type filter hook forward priority filter
    policy drop

    # PPPoE MTU
    oifname { "ppp0", "eno2" } tcp flags syn tcp option maxseg size set rt mtu

    iifname {
      "eno1",
    } oifname {
     "ppp0",
     "eno2",
    } counter accept comment "Allow trusted LAN to WAN"

    iifname "eno1" oifname "tailscale0" counter accept comment "Allow trusted LAN to Tailscale"

    iifname {
      "ppp0",
      "eno2",
    } oifname {
      "eno1",
    } ct state established,related counter accept comment "Allow established back to LANs"

    iifname "tailscale0" oifname "eno1" counter accept comment "Allow Tailscale to LAN"
  }
}

table ip nat {
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
  }

  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;
    oifname "ppp0" masquerade
    oifname "eno2" masquerade
  }
}
