# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/33635f22-a983-4437-8cba-6f2de2cda884";
      fsType = "ext4";
    };

  fileSystems."/backup" =
    { device = "backup";
      fsType = "zfs";
    };

  fileSystems."/backup/restic" =
    { device = "backup/restic";
      fsType = "zfs";
    };

  fileSystems."/pool" =
    { device = "pool";
      fsType = "zfs";
    };

  fileSystems."/pool/restic" =
    { device = "pool/restic";
      fsType = "zfs";
    };

  fileSystems."/pool/samba" =
    { device = "pool/samba";
      fsType = "zfs";
    };

  fileSystems."/pool/samba/melias122" =
    { device = "pool/samba/melias122";
      fsType = "zfs";
    };

  fileSystems."/pool/samba/public" =
    { device = "pool/samba/public";
      fsType = "zfs";
    };

  fileSystems."/pool/samba/timemachine" =
    { device = "pool/samba/timemachine";
      fsType = "zfs";
    };

  fileSystems."/pool/containers" =
    { device = "pool/containers";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/89743755-9000-44b6-93b9-1e64e64dd99b"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
